"""add media assets

Revision ID: 2462113d2a32
Revises: 9b761410e620
Create Date: 2026-08-01 13:32:48.466437

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2462113d2a32"
down_revision: str | Sequence[str] | None = "9b761410e620"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        "ix_media_owner_created", "media_assets", ["owner_id", "created_at"], unique=False
    )
    op.add_column("posts", sa.Column("media_asset_id", sa.UUID(), nullable=True))
    op.alter_column("posts", "image_url", existing_type=sa.VARCHAR(length=1000), nullable=True)
    op.create_foreign_key(
        None, "posts", "media_assets", ["media_asset_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.alter_column("posts", "image_url", existing_type=sa.VARCHAR(length=1000), nullable=False)
    op.drop_column("posts", "media_asset_id")
    op.drop_index("ix_media_owner_created", table_name="media_assets")
    op.drop_table("media_assets")
    # ### end Alembic commands ###
