"""add reels, stories and highlights

Revision ID: 315b82e3bfc7
Revises: 2462113d2a32
Create Date: 2026-08-01 14:07:50.930155

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "315b82e3bfc7"
down_revision: str | Sequence[str] | None = "2462113d2a32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "highlights",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=60), nullable=False),
        sa.Column("cover_url", sa.String(length=1000), nullable=True),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_highlights_owner_position", "highlights", ["owner_id", "position"], unique=False
    )
    op.create_table(
        "highlight_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("highlight_id", sa.UUID(), nullable=False),
        sa.Column("image_url", sa.String(length=1000), nullable=True),
        sa.Column("media_asset_id", sa.UUID(), nullable=True),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["highlight_id"], ["highlights.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["media_asset_id"], ["media_assets.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_highlight_items_highlight",
        "highlight_items",
        ["highlight_id", "position"],
        unique=False,
    )
    op.create_table(
        "reels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("video_url", sa.String(length=1000), nullable=True),
        sa.Column("media_asset_id", sa.UUID(), nullable=True),
        sa.Column("album_url", sa.String(length=1000), nullable=True),
        sa.Column("caption", sa.String(length=2200), nullable=True),
        sa.Column("likes_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("comments_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("views_count", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["media_asset_id"], ["media_assets.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_reels_author_created", "reels", ["author_id", "created_at"], unique=False)
    op.create_index("ix_reels_created", "reels", ["created_at"], unique=False)
    op.create_index("ix_reels_views", "reels", ["views_count"], unique=False)
    op.create_table(
        "stories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("image_url", sa.String(length=1000), nullable=True),
        sa.Column("media_asset_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["media_asset_id"], ["media_assets.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_stories_author_expires", "stories", ["author_id", "expires_at"], unique=False
    )
    op.create_index("ix_stories_expires", "stories", ["expires_at"], unique=False)
    op.create_table(
        "reel_likes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("reel_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["reel_id"], ["reels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reel_id", "user_id", name="uq_reel_like"),
    )
    op.create_index("ix_reel_likes_user", "reel_likes", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_reel_likes_user", table_name="reel_likes")
    op.drop_table("reel_likes")
    op.drop_index("ix_stories_expires", table_name="stories")
    op.drop_index("ix_stories_author_expires", table_name="stories")
    op.drop_table("stories")
    op.drop_index("ix_reels_views", table_name="reels")
    op.drop_index("ix_reels_created", table_name="reels")
    op.drop_index("ix_reels_author_created", table_name="reels")
    op.drop_table("reels")
    op.drop_index("ix_highlight_items_highlight", table_name="highlight_items")
    op.drop_table("highlight_items")
    op.drop_index("ix_highlights_owner_position", table_name="highlights")
    op.drop_table("highlights")
    # ### end Alembic commands ###
