"""add follows, profile links, pronouns and counters

Revision ID: 3bb503f3414b
Revises: 06f6278c0508
Create Date: 2026-07-30 19:46:11.733355

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3bb503f3414b"
down_revision: str | Sequence[str] | None = "06f6278c0508"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "follows",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("follower_id", sa.UUID(), nullable=False),
        sa.Column("following_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("follower_id <> following_id", name="ck_no_self_follow"),
        sa.ForeignKeyConstraint(["follower_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["following_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("follower_id", "following_id", name="uq_follow_pair"),
    )
    op.create_index(
        "ix_follows_follower_created", "follows", ["follower_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_follows_following_created", "follows", ["following_id", "created_at"], unique=False
    )
    op.add_column("users", sa.Column("pronouns", sa.String(length=40), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "links", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
    )
    op.add_column(
        "users", sa.Column("followers_count", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "users", sa.Column("following_count", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "users", sa.Column("posts_count", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "posts_count")
    op.drop_column("users", "following_count")
    op.drop_column("users", "followers_count")
    op.drop_column("users", "links")
    op.drop_column("users", "pronouns")
    op.drop_index("ix_follows_following_created", table_name="follows")
    op.drop_index("ix_follows_follower_created", table_name="follows")
    op.drop_table("follows")
    # ### end Alembic commands ###
