"""add hashtags, post tags, mentions and comment replies

Revision ID: abf7a0be6ced
Revises: 12842cb8c81b
Create Date: 2026-08-04 18:53:38.388132

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abf7a0be6ced"
down_revision: str | Sequence[str] | None = "12842cb8c81b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hashtags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tag", sa.String(length=100), nullable=False),
        sa.Column("posts_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hashtags_tag"), "hashtags", ["tag"], unique=True)
    op.create_table(
        "post_hashtags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("hashtag_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["hashtag_id"], ["hashtags.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("post_id", "hashtag_id", name="uq_post_hashtag"),
    )
    op.create_index("ix_post_hashtags_hashtag", "post_hashtags", ["hashtag_id"], unique=False)
    op.create_table(
        "post_tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("x", sa.Float(), nullable=True),
        sa.Column("y", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("post_id", "user_id", name="uq_post_tag"),
    )
    op.create_index("ix_post_tags_user", "post_tags", ["user_id"], unique=False)
    op.create_table(
        "mentions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=True),
        sa.Column("comment_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(post_id IS NOT NULL AND comment_id IS NULL) OR (post_id IS NULL AND comment_id IS NOT NULL)",
            name="ck_mention_one_target",
        ),
        sa.ForeignKeyConstraint(["comment_id"], ["comments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_mentions_user_created", "mentions", ["user_id", "created_at"], unique=False)
    op.create_index(
        "uq_mention_comment",
        "mentions",
        ["user_id", "comment_id"],
        unique=True,
        postgresql_where=sa.text("comment_id IS NOT NULL"),
    )
    op.create_index(
        "uq_mention_post",
        "mentions",
        ["user_id", "post_id"],
        unique=True,
        postgresql_where=sa.text("post_id IS NOT NULL"),
    )
    op.add_column("comments", sa.Column("parent_id", sa.UUID(), nullable=True))
    op.add_column(
        "comments", sa.Column("replies_count", sa.Integer(), server_default="0", nullable=False)
    )
    op.create_index(
        "ix_comments_parent_created", "comments", ["parent_id", "created_at"], unique=False
    )
    # Named explicitly: autogenerate emits None here, which leaves the downgrade
    # with no constraint to drop.
    op.create_foreign_key(
        "fk_comments_parent_id", "comments", "comments", ["parent_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_comments_parent_id", "comments", type_="foreignkey")
    op.drop_index("ix_comments_parent_created", table_name="comments")
    op.drop_column("comments", "replies_count")
    op.drop_column("comments", "parent_id")
    op.drop_index(
        "uq_mention_post", table_name="mentions", postgresql_where=sa.text("post_id IS NOT NULL")
    )
    op.drop_index(
        "uq_mention_comment",
        table_name="mentions",
        postgresql_where=sa.text("comment_id IS NOT NULL"),
    )
    op.drop_index("ix_mentions_user_created", table_name="mentions")
    op.drop_table("mentions")
    op.drop_index("ix_post_tags_user", table_name="post_tags")
    op.drop_table("post_tags")
    op.drop_index("ix_post_hashtags_hashtag", table_name="post_hashtags")
    op.drop_table("post_hashtags")
    op.drop_index(op.f("ix_hashtags_tag"), table_name="hashtags")
    op.drop_table("hashtags")
    # ### end Alembic commands ###
